title: "臺北市立誠正國民中學數理資優班"
description: "Math & Science Gifted and Talented Education Program"
url: "https://gateczjh.github.io"
baseurl: "https://gateczjh.github.io"

markdown: kramdown
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: zh
